services:
  proxy:
    build:
      context: "../reverse_proxy/"
      dockerfile: Dockerfile
      args:
        - PORT=3000
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "3000:3000"
    networks:
      - internal
      - public
  auth:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=auth
        - PORT=6000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/auth-service.cert
        - PRIVATE_KEY_PATH=cert/auth-service.key
        - PASSPHRASE=""
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "6000"
    networks:
      - auth
      - internal
    depends_on:
      db-auth:
        condition: service_healthy

  account:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=account
        - PORT=8000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/account-service.cert
        - PRIVATE_KEY_PATH=cert/account-service.key
        - PASSPHRASE=""
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "8000"
    networks:
      - account
      - internal
    depends_on:
      db-account:
        condition: service_healthy

  mail:
    build: "../mail/"
    ports:
      - "4000"
    networks:
      - internal

  db-account:
    build: "./db/account/"
    ports:
      - "5432"
    networks:
      - account
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

  db-auth:
    build: "./db/auth/"
    ports:
      - "5432"
    networks:
      - auth
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

networks:
  auth: {}
  account: {}
  internal: {}
  public: 
    driver: bridge
