services:
  auth:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=auth
        - PORT=6000
      target: final
    ports:
      - "6000:6000"
    networks:
      - auth
      - internal
    depends_on:
      db-auth:
        condition: service_healthy

  account:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=account
        - PORT=8000
      target: final
    ports:
      - "6500:8000"
    networks:
      - account
      - internal
    depends_on:
      db-account:
        condition: service_healthy

  mail:
    build: "../mail/"
    ports:
      - "4000:4000"
    networks:
      - internal

  db-account:
    build: "./db/account/"
    ports:
      - "3000:5432"
    networks:
      - account
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

  db-auth:
    build: "./db/auth/"
    ports:
      - "3500:5432"
    networks:
      - auth
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

networks:
  auth: {}
  account: {} 
  internal: 
    driver: bridge
